version: '2'

networks:
  default:
    driver: overlay

services:

  acquisition:
    image: xemuliam/docker-nifi
    ports:
      - 9091:8080
    environment:
      BANNER_TEXT: 'Acquisition Node'
      INSTANCE_ROLE: 'simple-node'

  ncm:
    image: xemuliam/docker-nifi
    ports:
      - 9091:8080
    environment:
      BANNER_TEXT: 'Processing Cluster'
      INSTANCE_ROLE: 'cluster-manager'

  worker:
    image: xemuliam/docker-nifi
    environment:
      BANNER_TEXT: 'Processing Node'
      INSTANCE_ROLE: 'cluster-node'

