version: '2'

services:

  node_zk:
    image: xemuliam/nifi
    container_name: node_zk_1
    ports:
      - 8080
    environment:
      IS_CLUSTER_NODE: 1
      ZK_NODES_LIST: 'node_zk_1'
      ZK_MYID: 1

  node:
    image: xemuliam/nifi
    ports:
      - 8080
    environment:
      IS_CLUSTER_NODE: 1
      ZK_NODES_LIST: 'node_zk_1'
