version: '2'

services:

  ncm:
    image: xemuliam/nifi:0.7.1
    ports:
      - 8080
    environment:
      IS_MANAGERER_NODE: true

  node:
    image: xemuliam/nifi:0.7.1
    ports:
      - 8080
    environment:
      IS_CLUSTER_NODE: yes
